// Copyright (c) 2019 PaddlePaddle Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/* DO NOT EDIT THIS FILE - it is machine generated */
#ifndef MMLCORE_MML_INIT_H
#define MMLCORE_MML_INIT_H

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

namespace mmlcore {

extern "C"
JNIEXPORT jlong JNICALL
Java_com_baidu_mmlcore_MMLPaddleLiteMachine_createMMLMachineService(JNIEnv *env,
                                                                    jobject thiz,
                                                                    jint back_end_type,
                                                                    jstring model_path,
                                                                    jint model_type,
                                                                    jint thread,
                                                                    jint power_mode);

}

#ifdef __cplusplus
}
#endif
#endif
